### ISSUE TITLE
Code highlighted in wrong place after saving a file

### ISSUE THREAD

**Issue by Ascii67** [sourcery-ai/sourcery#272]
### Checklist

- [x] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [x] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description
I added a custom rule in .sourcery.yaml which looks like this:
```
rules:
  - id: do-not-use-print-in-production-code
    description: Do not use print statements in production code.
    pattern: print
```
When I now start VSCode, the squiggly blue line is underneath the `print`statement. But when I now save the file, the squiggly blue line is right after the class definition:

![Bildschirmfoto vom 2022-09-04 19-49-42](https://user-images.githubusercontent.com/99130063/188326792-5a979daa-8796-4ca4-9866-cd92542e5469.png)

### Debug Information

IDE Version: 
VSCode 1.71.0

Sourcery Version: 
0.12.7

Operating system and Version:
Ubuntu 22.04
