### ISSUE TITLE
False positive for __init__.py :  Modules should have docstrings

### ISSUE THREAD

**Issue by Josverl** [sourcery-ai/sourcery#323]
### Description

Warnings / informationals are generated for __init__.py that are used as a module/package placeholder 
`ℹ️ Sourcery - Modules should have docstrings`

![image](https://user-images.githubusercontent.com/981654/217673694-b98ff06a-97ce-47f5-96af-19c90f989e0a.png)

### Code snippet that reproduces issue
an empty `__init__.py`

```python

```
### Debug Information
sourcery, version 1.0.4

IDE Version: 
Version: 1.75.0 (user setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by Josverl** [comment]
Quick-Fix:
Add  __init__.py fto the exclusions for thos rule

``` yaml
- id: docstrings-for-modules
  pattern: |
    '''!!!'''
    ...
  condition: pattern.in_module_scope()
  paths:
    exclude:
    - test_*.py
    - '*_test.py'
    - '__init__.py'
```
