### ISSUE TITLE
Can't ignore paths outside the project

### ISSUE THREAD

**Issue by xshapira** [sourcery-ai/sourcery#396]
Sourcery doesn't ignore paths outside the project. The errors often stick around even when you close the file, which adds redundant clutter. 

I'm using Jedi as a language server in VS Code.

![CleanShot 2023-10-26 at 17 14 06@2x](https://github.com/sourcery-ai/sourcery/assets/48856190/381abc51-1105-4fc7-a42e-f9875f7876b5)

![CleanShot 2023-10-26 at 17 38 26@2x](https://github.com/sourcery-ai/sourcery/assets/48856190/b586c2b5-689f-4ab4-91af-ae587d827754)

Here is my global `sourcery.yaml` config file:
```yaml
rule_settings:
  enable:
  - default
  - gpsg

ignore:
  - .venv/*
  - ~/.vscode/extensions/*
  - ~/.pyenv/versions/*

coding_assistant:
  enabled: true

```

IDE Version: 
VS Code 1.83.1

Sourcery Version: 
Sourcery 1.11.0

Operating system and Version:
macOS Monterey 12.7
