### ISSUE TITLE
mapping values are not allowed here

### ISSUE THREAD

**Issue by stsmrvestas** [sourcery-ai/sourcery#409]
### Checklist

- [X] I have searched the [Sourcery documentation](https://docs.sourcery.ai/) for the issue, and found nothing
- [X] I have read the common issues and fixes listed in the [Sourcery troubleshooting page](https://docs.sourcery.ai/Product/Troubleshooting/#troubleshooting), and found nothing
- [X] I have checked there are no open [bugs](https://github.com/sourcery-ai/sourcery/issues?q=label%3Abug) referencing the same bug or problem

### Description

I'm new, so apologies if this is a user error, however I'm getting this error from a pattern, which looks almost identical to what you have in your docs afaict. It is complaining when attempting review from CLI:
```
.sourcery.yaml:41:27-41:28 (root) mapping values are not allowed here
in .sourcery.yaml", line 42, column 28:
        pattern: class ${klass}:
                               ^ (line: 42)
```

### Code snippet that reproduces issue

```yaml
<cut>
rules:
  - id: service-class-naming
    description: Service class naming convention
    pattern: class ${klass}:
    condition: not klass.matches_regex("^[A-Z][a-zA-Z0-9]*Service(\(.*|):$")
    explanation: 'Service classes must be postfixed with "Service" - if you have additional classes in the same file, please move them to a separate file'
```

### Debug Information
IDE Version: 
PyCharm 2023.3.1 (Professional Edition)

Sourcery Version: 
sourcery, version 1.15.0

Operating system and Version:
OSX Sonoma 14.2.1 (23C71)

**Comment by ruancomelli** [comment]
Hello, @stsmrvestas! Thanks for reaching out!

The error message you are seeing here actually comes from our YAML parser. Because of the YAML syntax, our parser (correctly) interprets the line `pattern: class ${klass}:` as if you were building a _nested dictionary_ `{"pattern": {"class ${klass}": ""}}`. Strange, right?

To fix this, you can use a [multiline YAML string](https://yaml-multiline.info/):
```yaml
rules:
  - id: service-class-naming
    description: Service class naming convention
    pattern: |
      class ${klass}(...):
        ...
    condition: not klass.ends_with("Service")
    explanation: 'Service classes must be postfixed with "Service" - if you have additional classes in the same file, please move them to a separate file'
```

I have also fixed the [Sourcery pattern syntax](https://docs.sourcery.ai/Reference/Rules-and-In-Line-Suggestions/Custom-Rules/pattern-syntax/#complete-example) for you by using the [universal matcher `...`](https://docs.sourcery.ai/Reference/Rules-and-In-Line-Suggestions/Custom-Rules/pattern-syntax/#match-anything-using) and simplified the matching condition by using the [`ends_with`](https://docs.sourcery.ai/Reference/Rules-and-In-Line-Suggestions/Custom-Rules/conditions/#ends_with) conditional, which (I think?) is what your rule is about.

Please let me know if this does (or does not) work for you.
